### ISSUE TITLE
Support Portable Class Libraries

### ISSUE THREAD

**Issue by sharwell** [mausch/ReadOnlyCollections#2]
I'd love to reference this package from one of my other projects, but I found that it doesn't support the Portable Class Library. In particular, a build for **Profile 328** would be ideal. The following image shows the target selection for this profile:

![image](https://cloud.githubusercontent.com/assets/1408396/5425813/e186b768-82eb-11e4-8689-69cd4fcb0b3e.png)

**Comment by mausch** [comment]
Fast-forward to 2021, .net standard has superseded all that PCL stuff for a few years now.
