### ISSUE TITLE
How can we pass array of data and then convert it to dictionary?

### ISSUE THREAD

**Issue by joshidp** [mausch/ReadOnlyCollections#4]
Hi,

Thanks for the efforts.

One query, Can I pass an array of data and then convert into a dictionary inside the constructor?
So instead of 
 public ReadOnlyDictionaryWrapper(IDictionary<K, V> dict) 

ctor sign will be
 public ReadOnlyDictionaryWrapper(V[] data)  //V will have the key column too.

Is this a good way?

Thanks!

**Comment by mausch** [comment]
You can use https://github.com/mausch/ReadOnlyCollections/blob/master/ReadOnlyCollectionsExtensions/ExtensionMethods.cs#L64 or https://github.com/mausch/ReadOnlyCollections/blob/master/ReadOnlyCollectionsExtensions/ExtensionMethods.cs#L78

**Comment by joshidp** [comment]
Thanks for the reply.

I have used ReadOnlyDictionaryWrapper as abstract base class so that each child can have it's own custom validation and features.

**Comment by mausch** [comment]
Ah, fair enough. I'd recommend against inheriting from ReadOnlyDictionaryWrapper but that's an entirely different discussion :)

Can we close this now then?

**Comment by joshidp** [comment]
Yup, I am closing it. Thanks again.
